### ISSUE TITLE
More detailed build and installation instructions ?

### ISSUE THREAD

**Issue by gl-yziquel** [fennewald/nu_plugin_net#8] opened 2023-09-27 13:04 UTC
I'm new to nu shell plugins. The installation instructions are terse.

I tried `cargo build`. Just to check how things go. I got:

```console
error: current package believes it's in a workspace when it's not:
```

Please provide more detailed instructions. As of now, I do not know from the `README.md` how I should use the `register` command.

**Comment by kurokirasama** [comment] 2023-09-27 13:16
I think that you can build with:
```bash
cargo build --release
```
But I think that for this particular plugin isn't necessary.
Then you install with:
```bash
cargo install --path .
````
And finally, you register it with:
```bash
register path/to/bin/file
```
the path is (in ubuntu): `~/.cargo/bin/nu_plugin_net`.

**Comment by fennewald** [comment] 2023-09-27 13:33
Are you looking for something like this: #9 ? Regardless, the "current package believes it's in a workspace" is new. Any more steps to reproduce?

**Comment by gl-yziquel** [comment] 2023-09-27 18:26
The instructions in the PR work like a charm. I just was confused about nu plugins. This clarified it.

The "current package believes it's in a workspace" is what one gets with a naked `cargo build`, not with `cargo install --path .`.

@kurokirasama that user image of yours is from, arguably, the best anime of all time.

**Comment by fennewald** [comment] 2023-09-27 18:38
Interesting. Plain `cargo build` works for me, but seeing as it's not causing you problems anymore I think I'll close this issue. Thanks for submitting a PR!

**Closed as completed by fennewald** 2023-09-27 18:38 UTC

**Comment by kurokirasama** [comment] 2023-09-27 18:44
> The instructions in the PR work like a charm. I just was confused about nu plugins. This clarified it.
> 
> The "current package believes it's in a workspace" is what one gets with a naked `cargo build`, not with `cargo install --path .`.
> 
> @kurokirasama that user image of yours is from, arguably, the best anime of all time.

totally agree!

**Comment by gl-yziquel** [comment] 2023-09-27 19:27
> > The instructions in the PR work like a charm. I just was confused about nu plugins. This clarified it.
> > The "current package believes it's in a workspace" is what one gets with a naked `cargo build`, not with `cargo install --path .`.
> > @kurokirasama that user image of yours is from, arguably, the best anime of all time.
> 
> totally agree!

I'll keep digging.
